### ISSUE TITLE
Immense stuttering

### ISSUE THREAD

**Issue by Hibanan** [Fuar11/FrozenFood#1]
This mod seems to cause mini stutters when out and about in the world, and crazy lag when I leave food by a fire to thaw out, like borderline unplayable. Removing the mod immediately makes the stuttering go away. Trying to place an item makes the stuttering even worse. (And another thing I noticed is you can eat frozen food you find in a container, if you use space to eat it straight from the looting UI, instead of going back to your inventory, which, as expected, tells you it's frozen).

Melonloader - 0.6.1
TLD - Vanilla
Modlist:
02/14/2023  03:23 AM            55,296 AmbientLights.dll
04/07/2024  02:17 AM        11,712,512 BetterBases.dll
08/06/2023  02:12 AM            25,600 Bountiful_Foraging.dll
11/12/2023  11:30 AM            45,056 Candlelight.dll
04/07/2024  02:22 AM            58,368 CraftingRevisions.dll
04/07/2024  02:19 AM             9,728 DarkerNights.dll
04/07/2024  02:19 AM        22,134,784 DynamicTrees.dll
04/07/2024  02:20 AM            21,504 ExtraGraphicsSettings.dll
04/07/2024  02:24 AM            46,080 FuelManager.dll
04/07/2024  02:22 AM            40,448 GearSpawner.dll
10/20/2023  01:49 PM            32,256 GearToolbox.dll
04/07/2024  02:23 AM            30,208 KeyboardUtilities.dll
04/07/2024  02:21 AM            26,112 LocalizationUtilities.dll
04/07/2024  02:22 AM           176,640 ModComponent.dll
04/07/2024  02:21 AM            26,112 ModData.dll
06/22/2023  12:57 PM            55,808 ModSettings.dll
04/07/2024  02:25 AM            24,576 Moment.dll
04/07/2024  02:27 AM            87,040 MoreLockedDoors.dll
04/07/2024  02:28 AM            24,064 PlacingAnywhere.dll
04/07/2024  02:28 AM            89,088 RelentlessNight.dll
04/07/2024  02:31 AM             6,656 TinyTweaks-RunWithLantern.dll
04/07/2024  02:32 AM            10,240 UseTheWorstFirstAndDropStone.dll
---
10/20/2023  02:02 PM         6,838,086 AHandyToolbox.modcomponent
11/12/2023  11:31 AM         8,037,587 candlelight.modcomponent
08/06/2023  02:14 AM        28,962,647 DZ_Bountiful_Foraging_NoDLC.modcomponent
04/07/2024  02:23 AM           516,903 ForgeBlueprints.modcomponent
04/07/2024  02:24 AM           702,636 FuelManager.ModdersGearToolbox.modcomponent
04/07/2024  02:27 AM           588,777 morelockeddoors.modcomponent

**Comment by Fuar11** [comment]
The stuttering occurs mostly on lower end PCs. As a developer I don't experience any stuttering or low FPS when using the mod at all. There is a static performance hit when using any mod that hooks update methods (a result of MelonLoader) but Frozen Food does have computations which amplify that effect. There isn't much I can do about this. I've already optimized the mod several times in the past. Also, the more food you have the worse it'll be since it has to update more objects at once.

Sorry :(

**Comment by Hibanan** [comment]
I'm on a 5800x with 32 gigs and an rtx 3070, and I had about 15 cans of food sitting next to a barrel fire. If this is enough to make the game stutter so hard that it makes interacting with the UI difficult, you should probably put a disclaimer somewhere, right?

**Comment by Fuar11** [comment]
I have the same specs and I do not experience any stuttering. Do you have vsync enabled? Turn it off. I always suggest that. I've found that having vsync enabled causes stuttering.

**Comment by Hibanan** [comment]
Well, to reiterate, the base game (and the rest of my modlist) works fine, it’s specifically this mod, but once I’m at my PC again I can and let you know.
